const ruleType = [
    'RULE_program', 'RULE_block', 'RULE_begin_end_block', 'RULE_single_block_stmt', 'RULE_block_end', 'RULE_proc_block',
    'RULE_stmt', 'RULE_semicolon_stmt', 'RULE_exception_block', 'RULE_exception_block_item', 'RULE_null_stmt',
    'RULE_expr_stmt', 'RULE_assignment_stmt', 'RULE_assignment_stmt_item', 'RULE_assignment_stmt_single_item',
    'RULE_assignment_stmt_multiple_item', 'RULE_assignment_stmt_select_item', 'RULE_allocate_cursor_stmt',
    'RULE_associate_locator_stmt', 'RULE_begin_transaction_stmt', 'RULE_break_stmt', 'RULE_call_stmt',
    'RULE_declare_stmt', 'RULE_declare_block', 'RULE_declare_block_inplace', 'RULE_declare_stmt_item',
    'RULE_declare_var_item', 'RULE_declare_condition_item', 'RULE_declare_cursor_item', 'RULE_cursor_with_return',
    'RULE_cursor_without_return', 'RULE_declare_handler_item', 'RULE_declare_temporary_table_item',
    'RULE_create_table_stmt', 'RULE_create_local_temp_table_stmt', 'RULE_create_table_definition',
    'RULE_create_table_columns', 'RULE_create_table_columns_item', 'RULE_column_name',
    'RULE_create_table_column_inline_cons', 'RULE_create_table_column_cons', 'RULE_create_table_fk_action',
    'RULE_create_table_preoptions', 'RULE_create_table_preoptions_item', 'RULE_create_table_preoptions_td_item',
    'RULE_create_table_options', 'RULE_create_table_options_item', 'RULE_create_table_options_ora_item',
    'RULE_create_table_options_db2_item', 'RULE_create_table_options_td_item', 'RULE_create_table_options_hive_item',
    'RULE_create_table_hive_row_format', 'RULE_create_table_hive_row_format_fields',
    'RULE_create_table_options_mssql_item', 'RULE_create_table_options_mysql_item', 'RULE_alter_table_stmt',
    'RULE_alter_table_item', 'RULE_alter_table_add_constraint', 'RULE_alter_table_add_constraint_item', 'RULE_dtype',
    'RULE_dtype_len', 'RULE_dtype_attr', 'RULE_dtype_default', 'RULE_create_database_stmt',
    'RULE_create_database_option', 'RULE_create_function_stmt', 'RULE_create_function_return',
    'RULE_create_package_stmt', 'RULE_package_spec', 'RULE_package_spec_item', 'RULE_create_package_body_stmt',
    'RULE_package_body', 'RULE_package_body_item', 'RULE_create_procedure_stmt', 'RULE_create_routine_params',
    'RULE_create_routine_param_item', 'RULE_create_routine_options', 'RULE_create_routine_option', 'RULE_drop_stmt',
    'RULE_end_transaction_stmt', 'RULE_exec_stmt', 'RULE_if_stmt', 'RULE_if_plsql_stmt', 'RULE_if_tsql_stmt',
    'RULE_if_bteq_stmt', 'RULE_elseif_block', 'RULE_else_block', 'RULE_include_stmt', 'RULE_insert_stmt',
    'RULE_insert_stmt_cols', 'RULE_insert_stmt_rows', 'RULE_insert_stmt_row', 'RULE_insert_directory_stmt',
    'RULE_exit_stmt', 'RULE_get_diag_stmt', 'RULE_get_diag_stmt_item', 'RULE_get_diag_stmt_exception_item',
    'RULE_get_diag_stmt_rowcount_item', 'RULE_grant_stmt', 'RULE_grant_stmt_item', 'RULE_leave_stmt',
    'RULE_map_object_stmt', 'RULE_open_stmt', 'RULE_fetch_stmt', 'RULE_collect_stats_stmt', 'RULE_collect_stats_clause',
    'RULE_close_stmt', 'RULE_cmp_stmt', 'RULE_cmp_source', 'RULE_copy_from_local_stmt', 'RULE_copy_stmt',
    'RULE_copy_source', 'RULE_copy_target', 'RULE_copy_option', 'RULE_copy_file_option', 'RULE_commit_stmt',
    'RULE_create_index_stmt', 'RULE_create_index_col', 'RULE_index_storage_clause', 'RULE_index_mssql_storage_clause',
    'RULE_print_stmt', 'RULE_quit_stmt', 'RULE_raise_stmt', 'RULE_resignal_stmt', 'RULE_return_stmt',
    'RULE_rollback_stmt', 'RULE_set_session_option', 'RULE_set_current_schema_option', 'RULE_set_mssql_session_option',
    'RULE_set_teradata_session_option', 'RULE_signal_stmt', 'RULE_summary_stmt', 'RULE_truncate_stmt', 'RULE_use_stmt',
    'RULE_values_into_stmt', 'RULE_while_stmt', 'RULE_for_cursor_stmt', 'RULE_for_range_stmt', 'RULE_label',
    'RULE_using_clause', 'RULE_select_stmt', 'RULE_cte_select_stmt', 'RULE_cte_select_stmt_item',
    'RULE_cte_select_cols', 'RULE_fullselect_stmt', 'RULE_fullselect_stmt_item', 'RULE_fullselect_set_clause',
    'RULE_subselect_stmt', 'RULE_select_list', 'RULE_select_list_set', 'RULE_select_list_limit',
    'RULE_select_list_item', 'RULE_select_list_alias', 'RULE_select_list_asterisk', 'RULE_into_clause',
    'RULE_from_clause', 'RULE_from_table_clause', 'RULE_from_table_name_clause', 'RULE_from_subselect_clause',
    'RULE_from_join_clause', 'RULE_from_join_type_clause', 'RULE_from_table_values_clause',
    'RULE_from_table_values_row', 'RULE_from_alias_clause', 'RULE_table_name', 'RULE_where_clause',
    'RULE_group_by_clause', 'RULE_having_clause', 'RULE_qualify_clause', 'RULE_order_by_clause', 'RULE_select_options',
    'RULE_select_options_item', 'RULE_update_stmt', 'RULE_update_assignment', 'RULE_update_table', 'RULE_update_upsert',
    'RULE_merge_stmt', 'RULE_merge_table', 'RULE_merge_condition', 'RULE_merge_action', 'RULE_delete_stmt',
    'RULE_delete_alias', 'RULE_describe_stmt', 'RULE_bool_expr', 'RULE_bool_expr_atom', 'RULE_bool_expr_unary',
    'RULE_bool_expr_single_in', 'RULE_bool_expr_multi_in', 'RULE_bool_expr_binary', 'RULE_bool_expr_logical_operator',
    'RULE_bool_expr_binary_operator', 'RULE_expr', 'RULE_expr_atom', 'RULE_expr_interval', 'RULE_interval_item',
    'RULE_expr_concat', 'RULE_expr_concat_item', 'RULE_expr_case', 'RULE_expr_case_simple', 'RULE_expr_case_searched',
    'RULE_expr_cursor_attribute', 'RULE_expr_agg_window_func', 'RULE_expr_func_all_distinct',
    'RULE_expr_func_over_clause', 'RULE_expr_func_partition_by_clause', 'RULE_expr_spec_func', 'RULE_expr_func',
    'RULE_expr_func_params', 'RULE_func_param', 'RULE_expr_select', 'RULE_expr_file', 'RULE_hive', 'RULE_hive_item',
    'RULE_host', 'RULE_host_cmd', 'RULE_host_stmt', 'RULE_file_name', 'RULE_date_literal', 'RULE_timestamp_literal',
    'RULE_ident', 'RULE_string', 'RULE_int_number', 'RULE_dec_number', 'RULE_bool_literal', 'RULE_null_const',
    'RULE_non_reserved_words'
];

const tokenType = [];

module.exports = {
    ruleType,
    tokenType
};
